version: "3.7"

services:

  influxdb:
    image: influxdb:1.7.8-alpine
    ports:
      - 8086:8086
    volumes:
      - type: volume
        source: telemetry-data
        target: /var/lib/influxdb
    networks:
      - influx-network
    container_name: influx_server
  
  chronograf:
    depends_on:
      - influxdb
    image: chronograf:1.7.14-alpine
    ports:
      - 8888:8888
    volumes:
      - type: volume
        source: chronograf-data
        target: /var/lib/chronograf
    networks:
      - influx-network
    container_name: chronograf_server
    command:
      - --influxdb-url=http://influxdb:8086

volumes:
  telemetry-data:
  chronograf-data:

networks:
  influx-network:
    driver: bridge