version: "3.7"

services:

  influxdb:
    image: influxdb:1.7.8-alpine
    ports:
      - 8086:8086
    volumes:
      - type: volume
        source: influxdata
        target: /var/lib/influxdb
    container_name: influx_server
  
  chronograf:
    depends_on:
      - influxdb
    image: chronograf:1.7.14-alpine
    ports:
      - 8888:8888
    volumes:
      - type: volume
        source: chronografdata
        target: /var/lib/chronograf
    container_name: chronograf_server
    command:
      - --influxdb-url=http://influxdb:8086

volumes:
  influxdata:
  influxconfig:
  chronografdata: